name: calculadora_insulina_pediatrica
description: App para cálculo de dosis de insulina institucional GobCL.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  # === NUEVA DEPENDENCIA ===
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: GobCL
      fonts:
        - asset: assets/fonts/gobCL_Regular.otf
        - asset: assets/fonts/gobCL_Light.otf
          weight: 300
        - asset: assets/fonts/gobCL_Bold.otf
          weight: 700
        - asset: assets/fonts/gobCL_Heavy.otf
          weight: 900