name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # O el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Web
        # IMPORTANTE: Cambia 'calculadora_insulina' por el nombre exacto de tu repo
        run: flutter build web --release --base-href "/calculadora_insulina/"
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
